name: shopify-lakehouse

include:
  - compose/kafka.yml
  - compose/minio.yml
  - compose/nessie.yml
  - compose/flink.yml
  - compose/generator.yml
  - compose/dremio.yml
  - compose/dbt.yml
  - compose/airflow.yml
  - compose/spark.yml
  - compose/webhook-service.yml
  - compose/grafana.yml

networks:
  lakehouse:
    name: lakehouse
    driver: bridge
